name: 'Bump version on default branch'
description: 'Version on default branch must be incremented if major and minor version numbers are the same as on release branch'
author: 'petr.steckovic@vodafone.com'
inputs:
  released-version:
    description: Version has been released
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout default branch
      shell: bash
      run: |
        git checkout ${{ github.event.repository.default_branch }}
    - name: Determine increment required
      id: increment-version-on-default-branch
      shell: bash
      run: |
        currentVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        currentMajorVersion=$(echo $currentVersion | cut -d'.' -f1)
        currentMinorVersion=$(echo $currentVersion | cut -d'.' -f2)

        releasedMajorVersion=$(echo ${{ inputs.released-version }} | cut -d'.' -f1)
        releasedMinorVersion=$(echo ${{ inputs.released-version }} | cut -d'.' -f2)
        
        if [[ "${releasedMajorVersion}.${releasedMinorVersion}" == "${currentMajorVersion}.${currentMinorVersion}" ]]; then
          echo "incrementDefaultBranchVersion=true" >> $GITHUB_ENV
        else
          echo "No increment required"
        fi
    - name: Bump default branch to next release
      if: ${{ env.incrementDefaultBranchVersion == 'true' }}
      uses: stezsky/shared-actions/actions/bump-pom@main
      with:
        version: ${{ inputs.released-version }}-SNAPSHOT
        increment-minor: true
